services:
  web-server:
    build:
      context: .
      dockerfile: dockerfile
    image: allure_report_wdio_web # Menentukan nama image secara spesifik
    ports:
      - "3015:3000" # Port host 8080 ke port container 80
    container_name: allure_report_wdio_web_coun # Nama container 
